name: frappe_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  app_logger:
    path: ../app_logger
  dio: ^5.8.0+1
  equatable: ^2.0.7
  socket_io_client: ^3.1.2
  flutter:
    sdk: flutter
  frappe_dart:
    git:
      url: https://github.com/kinetsystems/frappe_dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
